import type { Lang } from "@/contexts/LanguageContext";

/**
 * Texte für „Himmel heute“ (/himmel-heute) in allen 13 Sprachen.
 * Platzhalter in {geschweiften Klammern} werden im Code ersetzt.
 * Nutzerwunsch 09.10.2026 ("ok erstell").
 */
export type MoonPhaseNames = [string, string, string, string, string, string, string, string];

export type SkyTodayText = {
  title: string; desc: string; h1: string; intro: string; asOf: string;
  moon: string; sun: string;
  h2Moon: string; illum: string; phases: MoonPhaseNames; nextFull: string; nextNew: string; constLabel: string;
  h2Planets: string; planetsNote: string;
  stEveLow: string; stEve: string; stAll: string; stMorn: string; stMornLow: string; stNone: string;
  eyeNaked: string; eyeAid: string; brightness: string; showSky: string;
  h2Local: string; localBtn: string; localHint: string; localDenied: string; rise: string; set: string; none: string; upAllDay: string;
  h2Events: string; evFull: string; evNew: string; evOpp: string; evElE: string; evElW: string; evPair: string;
  evMeteor: string; meteorMoon: string; evSolarTotal: string; evSolarAnn: string; partialIn: string;
  today: string; tomorrow: string; inDays: string;
  liveCta: string; h2Faq: string; faq: { q: string; a: string }[]; credit: string; keywords: string[];
  meteors: Record<MeteorId, string>;
  ecl2027aug: [string, string]; ecl2027feb: [string, string];
};

export type MeteorId = "QUA" | "LYR" | "ETA" | "PER" | "ORI" | "LEO" | "GEM";

const de: SkyTodayText = {
  title: "Himmel heute – welche Planeten sieht man heute Nacht?",
  desc: "Welche Planeten heute sichtbar sind, Mondphase heute, nächster Vollmond und kommende Himmelsereignisse – stündlich neu berechnet. Mit Auf- und Untergangszeiten für deinen Ort.",
  h1: "Himmel heute",
  intro: "Was du heute am Nachthimmel sehen kannst: Mondphase, sichtbare Planeten und die nächsten Himmelsereignisse – jede Stunde neu berechnet, am Handy und am PC.",
  asOf: "Stand: {time}",
  moon: "Mond", sun: "Sonne",
  h2Moon: "Der Mond heute", illum: "{pct} % beleuchtet",
  phases: ["Neumond", "Zunehmende Sichel", "Erstes Viertel (zunehmender Halbmond)", "Zunehmender Mond", "Vollmond", "Abnehmender Mond", "Letztes Viertel (abnehmender Halbmond)", "Abnehmende Sichel"],
  nextFull: "Nächster Vollmond", nextNew: "Nächster Neumond", constLabel: "Sternbild",
  h2Planets: "Welche Planeten sieht man heute?",
  planetsNote: "Gilt grob überall auf der Welt. Genaue Auf- und Untergangszeiten für deinen Ort findest du weiter unten.",
  stEveLow: "abends kurz nach Sonnenuntergang, tief im Westen", stEve: "am Abendhimmel", stAll: "fast die ganze Nacht", stMorn: "am Morgenhimmel", stMornLow: "morgens kurz vor Sonnenaufgang, tief im Osten", stNone: "nicht sichtbar – zu nah an der Sonne",
  eyeNaked: "mit bloßem Auge", eyeAid: "nur mit Fernglas oder Teleskop", brightness: "Helligkeit {m} mag", showSky: "Am Himmel zeigen",
  h2Local: "Zeiten für deinen Ort", localBtn: "Meinen Standort verwenden", localHint: "Die Zeiten werden nur in deinem Browser berechnet – dein Standort wird weder gespeichert noch gesendet.", localDenied: "Standort nicht verfügbar. Bitte erlaube den Standortzugriff.",
  rise: "Aufgang", set: "Untergang", none: "—", upAllDay: "geht nicht unter",
  h2Events: "Die nächsten Himmelsereignisse",
  evFull: "Vollmond", evNew: "Neumond",
  evOpp: "{p} in Opposition – am hellsten und die ganze Nacht sichtbar",
  evElE: "{p} am weitesten von der Sonne entfernt ({d}°) – beste Sicht am Abendhimmel",
  evElW: "{p} am weitesten von der Sonne entfernt ({d}°) – beste Sicht am Morgenhimmel",
  evPair: "{a} und {b} ganz nah beieinander ({d}°)",
  evMeteor: "{n}: Höhepunkt des Meteorstroms – bis zu {z} Sternschnuppen pro Stunde unter dunklem Himmel",
  meteorMoon: "Mondlicht: {pct} %",
  evSolarTotal: "Totale Sonnenfinsternis – total in: {r}", evSolarAnn: "Ringförmige Sonnenfinsternis – ringförmig in: {r}", partialIn: "Teilweise sichtbar: {r}",
  today: "heute", tomorrow: "morgen", inDays: "in {n} Tagen",
  liveCta: "Jetzt live am Himmel ansehen",
  h2Faq: "Fragen & Antworten",
  faq: [
    { q: "Welche Planeten kann man heute Nacht sehen?", a: "Das ändert sich von Woche zu Woche. Diese Seite berechnet jede Stunde neu, welche Planeten am Abend-, Nacht- oder Morgenhimmel stehen und welche zu nah an der Sonne sind. Mit bloßem Auge sichtbar sind Merkur, Venus, Mars, Jupiter und Saturn." },
    { q: "Wann ist der nächste Vollmond?", a: "Der nächste Vollmond ist am {date}." },
    { q: "Warum sieht man manche Planeten nicht?", a: "Steht ein Planet am Himmel zu nah an der Sonne, geht er fast gleichzeitig mit ihr auf und unter und wird von ihrem Licht überstrahlt. Erst wenn er sich weit genug von der Sonne entfernt hat, taucht er am Abend- oder Morgenhimmel wieder auf." },
  ],
  credit: "Positionen berechnet mit den Bahnformeln von Paul Schlyter (Genauigkeit wenige Bogenminuten), Sternbild-Grenzen der IAU. Finsternisse: NASA; Meteorströme: IMO.",
  keywords: ["Himmel heute", "welche Planeten sieht man heute", "Planeten heute Nacht", "Mondphase heute", "nächster Vollmond", "Vollmond Oktober 2026", "Sternschnuppen 2026", "Himmelsereignisse 2026", "Sonnenfinsternis 2027"],
  meteors: { QUA: "Quadrantiden", LYR: "Lyriden", ETA: "Eta-Aquariiden", PER: "Perseiden", ORI: "Orioniden", LEO: "Leoniden", GEM: "Geminiden" },
  ecl2027aug: ["Südspanien, Gibraltar, Marokko, Algerien, Tunesien, Libyen, Ägypten, Saudi-Arabien, Jemen, Somalia", "fast ganz Europa, große Teile Afrikas, Naher Osten"],
  ecl2027feb: ["Chile, Argentinien, Uruguay, Elfenbeinküste, Ghana, Togo, Benin, Nigeria", "große Teile Südamerikas und Westafrikas"],
};

const en: SkyTodayText = {
  title: "Sky Tonight – Which Planets Are Visible Tonight?",
  desc: "Which planets you can see tonight, today's Moon phase, the next full moon and upcoming sky events – recalculated every hour, with rise and set times for your location.",
  h1: "Sky Tonight",
  intro: "What you can see in the night sky today: Moon phase, visible planets and the next sky events – recalculated every hour, on phone and PC.",
  asOf: "As of {time}",
  moon: "Moon", sun: "Sun",
  h2Moon: "The Moon today", illum: "{pct}% illuminated",
  phases: ["New Moon", "Waxing Crescent", "First Quarter", "Waxing Gibbous", "Full Moon", "Waning Gibbous", "Last Quarter", "Waning Crescent"],
  nextFull: "Next full moon", nextNew: "Next new moon", constLabel: "Constellation",
  h2Planets: "Which planets are visible tonight?",
  planetsNote: "Roughly valid anywhere in the world. Exact rise and set times for your location are further down.",
  stEveLow: "in the evening just after sunset, low in the west", stEve: "in the evening sky", stAll: "almost all night", stMorn: "in the morning sky", stMornLow: "in the morning just before sunrise, low in the east", stNone: "not visible – too close to the Sun",
  eyeNaked: "naked eye", eyeAid: "binoculars or telescope needed", brightness: "Magnitude {m}", showSky: "Show in the sky",
  h2Local: "Times for your location", localBtn: "Use my location", localHint: "Times are calculated only in your browser – your location is never stored or sent.", localDenied: "Location not available. Please allow location access.",
  rise: "Rise", set: "Set", none: "—", upAllDay: "does not set",
  h2Events: "Upcoming sky events",
  evFull: "Full Moon", evNew: "New Moon",
  evOpp: "{p} at opposition – at its brightest and visible all night",
  evElE: "{p} at greatest elongation ({d}°) – best view in the evening sky",
  evElW: "{p} at greatest elongation ({d}°) – best view in the morning sky",
  evPair: "{a} and {b} very close together ({d}°)",
  evMeteor: "{n}: meteor shower peak – up to {z} shooting stars per hour under dark skies",
  meteorMoon: "Moonlight: {pct}%",
  evSolarTotal: "Total solar eclipse – total in: {r}", evSolarAnn: "Annular solar eclipse – annular in: {r}", partialIn: "Partial: {r}",
  today: "today", tomorrow: "tomorrow", inDays: "in {n} days",
  liveCta: "See it live in the sky now",
  h2Faq: "Questions & answers",
  faq: [
    { q: "Which planets can I see tonight?", a: "That changes from week to week. This page recalculates every hour which planets are in the evening, night or morning sky and which are too close to the Sun. Mercury, Venus, Mars, Jupiter and Saturn are visible to the naked eye." },
    { q: "When is the next full moon?", a: "The next full moon is on {date}." },
    { q: "Why can't I see some planets?", a: "When a planet is too close to the Sun in the sky, it rises and sets almost together with it and is lost in its glare. Only once it has moved far enough from the Sun does it reappear in the evening or morning sky." },
  ],
  credit: "Positions calculated with Paul Schlyter's orbital formulas (accuracy a few arcminutes), IAU constellation boundaries. Eclipses: NASA; meteor showers: IMO.",
  keywords: ["sky tonight", "what planets are visible tonight", "planets tonight", "moon phase today", "next full moon", "full moon October 2026", "meteor shower tonight", "sky events 2026", "solar eclipse 2027"],
  meteors: { QUA: "Quadrantids", LYR: "Lyrids", ETA: "Eta Aquariids", PER: "Perseids", ORI: "Orionids", LEO: "Leonids", GEM: "Geminids" },
  ecl2027aug: ["southern Spain, Gibraltar, Morocco, Algeria, Tunisia, Libya, Egypt, Saudi Arabia, Yemen, Somalia", "almost all of Europe, most of Africa, the Middle East"],
  ecl2027feb: ["Chile, Argentina, Uruguay, Ivory Coast, Ghana, Togo, Benin, Nigeria", "much of South America and West Africa"],
};

const es: SkyTodayText = {
  title: "El cielo esta noche – ¿qué planetas se ven hoy?",
  desc: "Qué planetas se ven esta noche, la fase lunar de hoy, la próxima luna llena y los próximos eventos del cielo – calculado cada hora, con salida y puesta para tu ubicación.",
  h1: "El cielo esta noche",
  intro: "Lo que puedes ver hoy en el cielo nocturno: fase lunar, planetas visibles y los próximos eventos del cielo – recalculado cada hora, en el móvil y en el PC.",
  asOf: "Actualizado: {time}",
  moon: "Luna", sun: "Sol",
  h2Moon: "La Luna hoy", illum: "{pct} % iluminada",
  phases: ["Luna nueva", "Luna creciente", "Cuarto creciente", "Gibosa creciente", "Luna llena", "Gibosa menguante", "Cuarto menguante", "Luna menguante"],
  nextFull: "Próxima luna llena", nextNew: "Próxima luna nueva", constLabel: "Constelación",
  h2Planets: "¿Qué planetas se ven esta noche?",
  planetsNote: "Válido aproximadamente en todo el mundo. Las horas exactas de salida y puesta para tu ubicación están más abajo.",
  stEveLow: "al anochecer, justo después de la puesta del Sol, bajo en el oeste", stEve: "en el cielo vespertino", stAll: "casi toda la noche", stMorn: "en el cielo matutino", stMornLow: "al amanecer, justo antes de la salida del Sol, bajo en el este", stNone: "no visible – demasiado cerca del Sol",
  eyeNaked: "a simple vista", eyeAid: "solo con prismáticos o telescopio", brightness: "Magnitud {m}", showSky: "Mostrar en el cielo",
  h2Local: "Horas para tu ubicación", localBtn: "Usar mi ubicación", localHint: "Las horas se calculan solo en tu navegador: tu ubicación no se guarda ni se envía.", localDenied: "Ubicación no disponible. Permite el acceso a la ubicación.",
  rise: "Salida", set: "Puesta", none: "—", upAllDay: "no se pone",
  h2Events: "Próximos eventos del cielo",
  evFull: "Luna llena", evNew: "Luna nueva",
  evOpp: "{p} en oposición – en su máximo brillo y visible toda la noche",
  evElE: "{p} en su máxima elongación ({d}°) – mejor vista en el cielo vespertino",
  evElW: "{p} en su máxima elongación ({d}°) – mejor vista en el cielo matutino",
  evPair: "{a} y {b} muy juntos ({d}°)",
  evMeteor: "{n}: máximo de la lluvia de meteoros – hasta {z} estrellas fugaces por hora con cielo oscuro",
  meteorMoon: "Luz lunar: {pct} %",
  evSolarTotal: "Eclipse solar total – total en: {r}", evSolarAnn: "Eclipse solar anular – anular en: {r}", partialIn: "Parcial: {r}",
  today: "hoy", tomorrow: "mañana", inDays: "en {n} días",
  liveCta: "Verlo ahora en vivo en el cielo",
  h2Faq: "Preguntas y respuestas",
  faq: [
    { q: "¿Qué planetas se pueden ver esta noche?", a: "Cambia de semana en semana. Esta página recalcula cada hora qué planetas están en el cielo vespertino, nocturno o matutino y cuáles están demasiado cerca del Sol. Mercurio, Venus, Marte, Júpiter y Saturno se ven a simple vista." },
    { q: "¿Cuándo es la próxima luna llena?", a: "La próxima luna llena es el {date}." },
    { q: "¿Por qué no se ven algunos planetas?", a: "Cuando un planeta está demasiado cerca del Sol en el cielo, sale y se pone casi a la vez que él y queda oculto por su brillo. Solo cuando se aleja lo suficiente del Sol vuelve a aparecer en el cielo vespertino o matutino." },
  ],
  credit: "Posiciones calculadas con las fórmulas orbitales de Paul Schlyter (precisión de pocos minutos de arco), límites de constelaciones de la UAI. Eclipses: NASA; lluvias de meteoros: IMO.",
  keywords: ["cielo esta noche", "qué planetas se ven hoy", "planetas visibles esta noche", "fase lunar hoy", "próxima luna llena", "luna llena octubre 2026", "lluvia de estrellas 2026", "eclipse solar 2027"],
  meteors: { QUA: "Cuadrántidas", LYR: "Líridas", ETA: "Eta Acuáridas", PER: "Perseidas", ORI: "Oriónidas", LEO: "Leónidas", GEM: "Gemínidas" },
  ecl2027aug: ["sur de España, Gibraltar, Marruecos, Argelia, Túnez, Libia, Egipto, Arabia Saudí, Yemen, Somalia", "casi toda Europa, gran parte de África, Oriente Medio"],
  ecl2027feb: ["Chile, Argentina, Uruguay, Costa de Marfil, Ghana, Togo, Benín, Nigeria", "gran parte de Sudamérica y de África occidental"],
};

const fr: SkyTodayText = {
  title: "Le ciel ce soir – quelles planètes voir aujourd'hui ?",
  desc: "Quelles planètes sont visibles ce soir, la phase de la Lune aujourd'hui, la prochaine pleine lune et les prochains événements célestes – recalculé chaque heure, avec lever et coucher pour ta position.",
  h1: "Le ciel ce soir",
  intro: "Ce que tu peux voir aujourd'hui dans le ciel nocturne : phase de la Lune, planètes visibles et prochains événements célestes – recalculé chaque heure, sur mobile et PC.",
  asOf: "Mis à jour : {time}",
  moon: "Lune", sun: "Soleil",
  h2Moon: "La Lune aujourd'hui", illum: "éclairée à {pct} %",
  phases: ["Nouvelle lune", "Premier croissant", "Premier quartier", "Lune gibbeuse croissante", "Pleine lune", "Lune gibbeuse décroissante", "Dernier quartier", "Dernier croissant"],
  nextFull: "Prochaine pleine lune", nextNew: "Prochaine nouvelle lune", constLabel: "Constellation",
  h2Planets: "Quelles planètes voir ce soir ?",
  planetsNote: "Valable à peu près partout dans le monde. Les heures exactes de lever et de coucher pour ta position sont plus bas.",
  stEveLow: "le soir juste après le coucher du Soleil, bas à l'ouest", stEve: "dans le ciel du soir", stAll: "presque toute la nuit", stMorn: "dans le ciel du matin", stMornLow: "le matin juste avant le lever du Soleil, bas à l'est", stNone: "invisible – trop près du Soleil",
  eyeNaked: "à l'œil nu", eyeAid: "jumelles ou télescope nécessaires", brightness: "Magnitude {m}", showSky: "Montrer dans le ciel",
  h2Local: "Heures pour ta position", localBtn: "Utiliser ma position", localHint: "Les heures sont calculées uniquement dans ton navigateur : ta position n'est ni enregistrée ni envoyée.", localDenied: "Position indisponible. Autorise l'accès à la localisation.",
  rise: "Lever", set: "Coucher", none: "—", upAllDay: "ne se couche pas",
  h2Events: "Prochains événements célestes",
  evFull: "Pleine lune", evNew: "Nouvelle lune",
  evOpp: "{p} à l'opposition – au plus brillant et visible toute la nuit",
  evElE: "{p} à sa plus grande élongation ({d}°) – meilleure visibilité le soir",
  evElW: "{p} à sa plus grande élongation ({d}°) – meilleure visibilité le matin",
  evPair: "{a} et {b} tout proches l'un de l'autre ({d}°)",
  evMeteor: "{n} : maximum de l'essaim – jusqu'à {z} étoiles filantes par heure sous un ciel noir",
  meteorMoon: "Clair de lune : {pct} %",
  evSolarTotal: "Éclipse totale de Soleil – totale en : {r}", evSolarAnn: "Éclipse annulaire de Soleil – annulaire en : {r}", partialIn: "Partielle : {r}",
  today: "aujourd'hui", tomorrow: "demain", inDays: "dans {n} jours",
  liveCta: "Voir maintenant en direct dans le ciel",
  h2Faq: "Questions et réponses",
  faq: [
    { q: "Quelles planètes peut-on voir ce soir ?", a: "Cela change d'une semaine à l'autre. Cette page recalcule chaque heure quelles planètes sont dans le ciel du soir, de la nuit ou du matin et lesquelles sont trop près du Soleil. Mercure, Vénus, Mars, Jupiter et Saturne sont visibles à l'œil nu." },
    { q: "Quand a lieu la prochaine pleine lune ?", a: "La prochaine pleine lune a lieu le {date}." },
    { q: "Pourquoi certaines planètes sont-elles invisibles ?", a: "Quand une planète est trop près du Soleil dans le ciel, elle se lève et se couche presque en même temps que lui et disparaît dans sa lumière. Elle ne réapparaît dans le ciel du soir ou du matin qu'une fois assez éloignée du Soleil." },
  ],
  credit: "Positions calculées avec les formules orbitales de Paul Schlyter (précision de quelques minutes d'arc), limites des constellations de l'UAI. Éclipses : NASA ; essaims de météores : IMO.",
  keywords: ["ciel ce soir", "quelles planètes voir ce soir", "planètes visibles ce soir", "phase de la lune aujourd'hui", "prochaine pleine lune", "pleine lune octobre 2026", "étoiles filantes 2026", "éclipse solaire 2027"],
  meteors: { QUA: "Quadrantides", LYR: "Lyrides", ETA: "Êta Aquarides", PER: "Perséides", ORI: "Orionides", LEO: "Léonides", GEM: "Géminides" },
  ecl2027aug: ["sud de l'Espagne, Gibraltar, Maroc, Algérie, Tunisie, Libye, Égypte, Arabie saoudite, Yémen, Somalie", "presque toute l'Europe, une grande partie de l'Afrique, le Moyen-Orient"],
  ecl2027feb: ["Chili, Argentine, Uruguay, Côte d'Ivoire, Ghana, Togo, Bénin, Nigeria", "une grande partie de l'Amérique du Sud et de l'Afrique de l'Ouest"],
};

const pt: SkyTodayText = {
  title: "O céu hoje à noite – que planetas dá para ver hoje?",
  desc: "Que planetas estão visíveis hoje à noite, a fase da Lua hoje, a próxima lua cheia e os próximos eventos no céu – recalculado a cada hora, com nascer e pôr para sua localização.",
  h1: "O céu hoje à noite",
  intro: "O que você pode ver hoje no céu noturno: fase da Lua, planetas visíveis e os próximos eventos no céu – recalculado a cada hora, no celular e no PC.",
  asOf: "Atualizado: {time}",
  moon: "Lua", sun: "Sol",
  h2Moon: "A Lua hoje", illum: "{pct}% iluminada",
  phases: ["Lua nova", "Lua crescente", "Quarto crescente", "Crescente gibosa", "Lua cheia", "Minguante gibosa", "Quarto minguante", "Lua minguante"],
  nextFull: "Próxima lua cheia", nextNew: "Próxima lua nova", constLabel: "Constelação",
  h2Planets: "Que planetas dá para ver hoje à noite?",
  planetsNote: "Vale aproximadamente para o mundo todo. Os horários exatos de nascer e pôr para sua localização estão mais abaixo.",
  stEveLow: "à noitinha, logo após o pôr do Sol, baixo no oeste", stEve: "no céu do anoitecer", stAll: "quase a noite toda", stMorn: "no céu da madrugada", stMornLow: "de madrugada, pouco antes do nascer do Sol, baixo no leste", stNone: "não visível – perto demais do Sol",
  eyeNaked: "a olho nu", eyeAid: "só com binóculo ou telescópio", brightness: "Magnitude {m}", showSky: "Mostrar no céu",
  h2Local: "Horários para sua localização", localBtn: "Usar minha localização", localHint: "Os horários são calculados só no seu navegador – sua localização não é salva nem enviada.", localDenied: "Localização indisponível. Permita o acesso à localização.",
  rise: "Nascer", set: "Pôr", none: "—", upAllDay: "não se põe",
  h2Events: "Próximos eventos no céu",
  evFull: "Lua cheia", evNew: "Lua nova",
  evOpp: "{p} em oposição – no auge do brilho e visível a noite toda",
  evElE: "{p} na máxima elongação ({d}°) – melhor visão no céu do anoitecer",
  evElW: "{p} na máxima elongação ({d}°) – melhor visão no céu da madrugada",
  evPair: "{a} e {b} bem pertinho ({d}°)",
  evMeteor: "{n}: pico da chuva de meteoros – até {z} estrelas cadentes por hora com céu escuro",
  meteorMoon: "Luz da Lua: {pct}%",
  evSolarTotal: "Eclipse solar total – total em: {r}", evSolarAnn: "Eclipse solar anular – anular em: {r}", partialIn: "Parcial: {r}",
  today: "hoje", tomorrow: "amanhã", inDays: "em {n} dias",
  liveCta: "Ver agora ao vivo no céu",
  h2Faq: "Perguntas e respostas",
  faq: [
    { q: "Que planetas dá para ver hoje à noite?", a: "Isso muda de semana para semana. Esta página recalcula a cada hora quais planetas estão no céu do anoitecer, da noite ou da madrugada e quais estão perto demais do Sol. Mercúrio, Vênus, Marte, Júpiter e Saturno são visíveis a olho nu." },
    { q: "Quando é a próxima lua cheia?", a: "A próxima lua cheia é em {date}." },
    { q: "Por que não dá para ver alguns planetas?", a: "Quando um planeta está perto demais do Sol no céu, ele nasce e se põe quase junto com o Sol e some no brilho dele. Só depois de se afastar o bastante do Sol ele volta a aparecer no céu do anoitecer ou da madrugada." },
  ],
  credit: "Posições calculadas com as fórmulas orbitais de Paul Schlyter (precisão de poucos minutos de arco), limites das constelações da UAI. Eclipses: NASA; chuvas de meteoros: IMO.",
  keywords: ["céu hoje à noite", "que planetas dá para ver hoje", "planetas visíveis hoje", "fase da lua hoje", "próxima lua cheia", "lua cheia outubro 2026", "chuva de meteoros 2026", "eclipse solar 2027"],
  meteors: { QUA: "Quadrântidas", LYR: "Líridas", ETA: "Eta Aquáridas", PER: "Perseidas", ORI: "Orionídeas", LEO: "Leônidas", GEM: "Geminídeas" },
  ecl2027aug: ["sul da Espanha, Gibraltar, Marrocos, Argélia, Tunísia, Líbia, Egito, Arábia Saudita, Iêmen, Somália", "quase toda a Europa, grande parte da África, Oriente Médio"],
  ecl2027feb: ["Chile, Argentina, Uruguai, Costa do Marfim, Gana, Togo, Benin, Nigéria", "grande parte da América do Sul e da África Ocidental"],
};

const tr: SkyTodayText = {
  title: "Bu gece gökyüzü – bu gece hangi gezegenler görünüyor?",
  desc: "Bu gece hangi gezegenlerin göründüğü, bugünkü Ay evresi, sonraki dolunay ve yaklaşan gökyüzü olayları – her saat yeniden hesaplanır, konumun için doğuş ve batış saatleriyle.",
  h1: "Bu gece gökyüzü",
  intro: "Bugün gece gökyüzünde neler görebileceğin: Ay evresi, görünen gezegenler ve yaklaşan gökyüzü olayları – her saat yeniden hesaplanır, telefonda ve bilgisayarda.",
  asOf: "Güncelleme: {time}",
  moon: "Ay", sun: "Güneş",
  h2Moon: "Bugün Ay", illum: "%{pct} aydınlık",
  phases: ["Yeni Ay", "Büyüyen hilal", "İlk dördün", "Büyüyen şişkin Ay", "Dolunay", "Küçülen şişkin Ay", "Son dördün", "Küçülen hilal"],
  nextFull: "Sonraki dolunay", nextNew: "Sonraki yeni Ay", constLabel: "Takımyıldız",
  h2Planets: "Bu gece hangi gezegenler görünüyor?",
  planetsNote: "Dünyanın hemen her yerinde aşağı yukarı geçerlidir. Konumun için kesin doğuş ve batış saatleri aşağıda.",
  stEveLow: "akşam gün batımından hemen sonra, batıda alçakta", stEve: "akşam gökyüzünde", stAll: "neredeyse bütün gece", stMorn: "sabah gökyüzünde", stMornLow: "sabah gün doğumundan hemen önce, doğuda alçakta", stNone: "görünmüyor – Güneş'e çok yakın",
  eyeNaked: "çıplak gözle", eyeAid: "sadece dürbün veya teleskopla", brightness: "Parlaklık {m} kadir", showSky: "Gökyüzünde göster",
  h2Local: "Konumun için saatler", localBtn: "Konumumu kullan", localHint: "Saatler yalnızca tarayıcında hesaplanır – konumun kaydedilmez ve gönderilmez.", localDenied: "Konum alınamadı. Lütfen konum erişimine izin ver.",
  rise: "Doğuş", set: "Batış", none: "—", upAllDay: "batmıyor",
  h2Events: "Yaklaşan gökyüzü olayları",
  evFull: "Dolunay", evNew: "Yeni Ay",
  evOpp: "{p} karşı konumda – en parlak hâlinde ve bütün gece görünür",
  evElE: "{p} Güneş'ten en uzak noktada ({d}°) – akşam gökyüzünde en iyi görünüm",
  evElW: "{p} Güneş'ten en uzak noktada ({d}°) – sabah gökyüzünde en iyi görünüm",
  evPair: "{a} ve {b} birbirine çok yakın ({d}°)",
  evMeteor: "{n}: meteor yağmurunun zirvesi – karanlık gökyüzünde saatte {z} kayan yıldıza kadar",
  meteorMoon: "Ay ışığı: %{pct}",
  evSolarTotal: "Tam Güneş tutulması – tam olarak: {r}", evSolarAnn: "Halkalı Güneş tutulması – halkalı olarak: {r}", partialIn: "Parçalı: {r}",
  today: "bugün", tomorrow: "yarın", inDays: "{n} gün sonra",
  liveCta: "Şimdi gökyüzünde canlı izle",
  h2Faq: "Sorular ve cevaplar",
  faq: [
    { q: "Bu gece hangi gezegenler görülebilir?", a: "Bu haftadan haftaya değişir. Bu sayfa her saat hangi gezegenlerin akşam, gece veya sabah gökyüzünde olduğunu ve hangilerinin Güneş'e çok yakın olduğunu yeniden hesaplar. Merkür, Venüs, Mars, Jüpiter ve Satürn çıplak gözle görülebilir." },
    { q: "Sonraki dolunay ne zaman?", a: "Sonraki dolunay {date} tarihinde." },
    { q: "Neden bazı gezegenler görünmüyor?", a: "Bir gezegen gökyüzünde Güneş'e çok yakınsa onunla neredeyse aynı anda doğup batar ve ışığında kaybolur. Güneş'ten yeterince uzaklaştığında akşam ya da sabah gökyüzünde yeniden ortaya çıkar." },
  ],
  credit: "Konumlar Paul Schlyter'in yörünge formülleriyle hesaplanmıştır (doğruluk birkaç yay dakikası), takımyıldız sınırları IAU'ya göre. Tutulmalar: NASA; meteor yağmurları: IMO.",
  keywords: ["bu gece gökyüzü", "bu gece hangi gezegenler görünüyor", "bugün ay evresi", "sonraki dolunay", "dolunay ekim 2026", "meteor yağmuru 2026", "güneş tutulması 2027"],
  meteors: { QUA: "Quadrantidler", LYR: "Liridler", ETA: "Eta Akuaridler", PER: "Perseidler", ORI: "Orionidler", LEO: "Leonidler", GEM: "Geminidler" },
  ecl2027aug: ["güney İspanya, Cebelitarık, Fas, Cezayir, Tunus, Libya, Mısır, Suudi Arabistan, Yemen, Somali", "Avrupa'nın neredeyse tamamı, Afrika'nın büyük kısmı, Orta Doğu"],
  ecl2027feb: ["Şili, Arjantin, Uruguay, Fildişi Sahili, Gana, Togo, Benin, Nijerya", "Güney Amerika ve Batı Afrika'nın büyük kısmı"],
};

const ru: SkyTodayText = {
  title: "Небо сегодня – какие планеты видны этой ночью?",
  desc: "Какие планеты видны сегодня ночью, фаза Луны сегодня, ближайшее полнолуние и предстоящие небесные события – пересчитывается каждый час, с восходом и заходом для твоего места.",
  h1: "Небо сегодня",
  intro: "Что можно увидеть сегодня на ночном небе: фаза Луны, видимые планеты и ближайшие небесные события – пересчитывается каждый час, на телефоне и на ПК.",
  asOf: "Обновлено: {time}",
  moon: "Луна", sun: "Солнце",
  h2Moon: "Луна сегодня", illum: "освещена на {pct} %",
  phases: ["Новолуние", "Растущий серп", "Первая четверть", "Растущая Луна", "Полнолуние", "Убывающая Луна", "Последняя четверть", "Убывающий серп"],
  nextFull: "Ближайшее полнолуние", nextNew: "Ближайшее новолуние", constLabel: "Созвездие",
  h2Planets: "Какие планеты видны сегодня ночью?",
  planetsNote: "Примерно верно для любой точки мира. Точное время восхода и захода для твоего места – ниже.",
  stEveLow: "вечером сразу после заката, низко на западе", stEve: "на вечернем небе", stAll: "почти всю ночь", stMorn: "на утреннем небе", stMornLow: "утром незадолго до восхода Солнца, низко на востоке", stNone: "не видна – слишком близко к Солнцу",
  eyeNaked: "невооружённым глазом", eyeAid: "только в бинокль или телескоп", brightness: "Блеск {m}ᵐ", showSky: "Показать на небе",
  h2Local: "Время для твоего места", localBtn: "Использовать моё местоположение", localHint: "Время рассчитывается только в твоём браузере – местоположение не сохраняется и не отправляется.", localDenied: "Местоположение недоступно. Разреши доступ к геолокации.",
  rise: "Восход", set: "Заход", none: "—", upAllDay: "не заходит",
  h2Events: "Ближайшие небесные события",
  evFull: "Полнолуние", evNew: "Новолуние",
  evOpp: "{p} в противостоянии – ярче всего и видна всю ночь",
  evElE: "{p} в наибольшей элонгации ({d}°) – лучше всего видна вечером",
  evElW: "{p} в наибольшей элонгации ({d}°) – лучше всего видна утром",
  evPair: "{a} и {b} совсем рядом ({d}°)",
  evMeteor: "{n}: максимум метеорного потока – до {z} метеоров в час на тёмном небе",
  meteorMoon: "Лунный свет: {pct} %",
  evSolarTotal: "Полное солнечное затмение – полная фаза: {r}", evSolarAnn: "Кольцеобразное солнечное затмение – кольцо видно: {r}", partialIn: "Частное: {r}",
  today: "сегодня", tomorrow: "завтра", inDays: "через {n} дн.",
  liveCta: "Посмотреть на небе вживую",
  h2Faq: "Вопросы и ответы",
  faq: [
    { q: "Какие планеты можно увидеть сегодня ночью?", a: "Это меняется от недели к неделе. Эта страница каждый час заново рассчитывает, какие планеты находятся на вечернем, ночном или утреннем небе, а какие слишком близко к Солнцу. Меркурий, Венера, Марс, Юпитер и Сатурн видны невооружённым глазом." },
    { q: "Когда ближайшее полнолуние?", a: "Ближайшее полнолуние – {date}." },
    { q: "Почему некоторые планеты не видны?", a: "Если планета на небе слишком близко к Солнцу, она восходит и заходит почти одновременно с ним и теряется в его свете. Лишь отойдя от Солнца достаточно далеко, она снова появляется на вечернем или утреннем небе." },
  ],
  credit: "Положения рассчитаны по орбитальным формулам Пола Шлайтера (точность – несколько угловых минут), границы созвездий – МАС. Затмения: NASA; метеорные потоки: IMO.",
  keywords: ["небо сегодня", "какие планеты видны сегодня", "фаза луны сегодня", "ближайшее полнолуние", "полнолуние октябрь 2026", "звездопад 2026", "солнечное затмение 2027"],
  meteors: { QUA: "Квадрантиды", LYR: "Лириды", ETA: "Эта-Аквариды", PER: "Персеиды", ORI: "Ориониды", LEO: "Леониды", GEM: "Геминиды" },
  ecl2027aug: ["юг Испании, Гибралтар, Марокко, Алжир, Тунис, Ливия, Египет, Саудовская Аравия, Йемен, Сомали", "почти вся Европа, большая часть Африки, Ближний Восток"],
  ecl2027feb: ["Чили, Аргентина, Уругвай, Кот-д’Ивуар, Гана, Того, Бенин, Нигерия", "большая часть Южной Америки и Западной Африки"],
};

const el: SkyTodayText = {
  title: "Ο ουρανός απόψε – ποιοι πλανήτες φαίνονται σήμερα;",
  desc: "Ποιοι πλανήτες φαίνονται απόψε, η φάση της Σελήνης σήμερα, η επόμενη πανσέληνος και τα επόμενα ουράνια φαινόμενα – υπολογίζεται κάθε ώρα, με ανατολή και δύση για την τοποθεσία σου.",
  h1: "Ο ουρανός απόψε",
  intro: "Τι μπορείς να δεις σήμερα στον νυχτερινό ουρανό: φάση της Σελήνης, ορατοί πλανήτες και τα επόμενα ουράνια φαινόμενα – υπολογίζεται κάθε ώρα, σε κινητό και PC.",
  asOf: "Ενημέρωση: {time}",
  moon: "Σελήνη", sun: "Ήλιος",
  h2Moon: "Η Σελήνη σήμερα", illum: "φωτισμένη κατά {pct}%",
  phases: ["Νέα Σελήνη", "Αύξων μηνίσκος", "Πρώτο τέταρτο", "Αύξουσα αμφίκυρτη", "Πανσέληνος", "Φθίνουσα αμφίκυρτη", "Τελευταίο τέταρτο", "Φθίνων μηνίσκος"],
  nextFull: "Επόμενη πανσέληνος", nextNew: "Επόμενη νέα Σελήνη", constLabel: "Αστερισμός",
  h2Planets: "Ποιοι πλανήτες φαίνονται απόψε;",
  planetsNote: "Ισχύει περίπου παντού στον κόσμο. Ακριβείς ώρες ανατολής και δύσης για την τοποθεσία σου θα βρεις πιο κάτω.",
  stEveLow: "το βράδυ αμέσως μετά τη δύση του Ήλιου, χαμηλά στη δύση", stEve: "στον βραδινό ουρανό", stAll: "σχεδόν όλη τη νύχτα", stMorn: "στον πρωινό ουρανό", stMornLow: "το πρωί λίγο πριν την ανατολή του Ήλιου, χαμηλά στην ανατολή", stNone: "δεν φαίνεται – πολύ κοντά στον Ήλιο",
  eyeNaked: "με γυμνό μάτι", eyeAid: "μόνο με κιάλια ή τηλεσκόπιο", brightness: "Λαμπρότητα {m} mag", showSky: "Δείξε στον ουρανό",
  h2Local: "Ώρες για την τοποθεσία σου", localBtn: "Χρήση της τοποθεσίας μου", localHint: "Οι ώρες υπολογίζονται μόνο στον browser σου – η τοποθεσία σου ούτε αποθηκεύεται ούτε αποστέλλεται.", localDenied: "Η τοποθεσία δεν είναι διαθέσιμη. Επίτρεψε την πρόσβαση στην τοποθεσία.",
  rise: "Ανατολή", set: "Δύση", none: "—", upAllDay: "δεν δύει",
  h2Events: "Τα επόμενα ουράνια φαινόμενα",
  evFull: "Πανσέληνος", evNew: "Νέα Σελήνη",
  evOpp: "{p} σε αντίθεση – στη μέγιστη λαμπρότητα και ορατός όλη τη νύχτα",
  evElE: "{p} στη μέγιστη αποχή ({d}°) – καλύτερη θέα στον βραδινό ουρανό",
  evElW: "{p} στη μέγιστη αποχή ({d}°) – καλύτερη θέα στον πρωινό ουρανό",
  evPair: "{a} και {b} πολύ κοντά ({d}°)",
  evMeteor: "{n}: μέγιστο της βροχής μετεωριτών – έως {z} διάττοντες την ώρα σε σκοτεινό ουρανό",
  meteorMoon: "Σεληνόφως: {pct}%",
  evSolarTotal: "Ολική έκλειψη Ηλίου – ολική σε: {r}", evSolarAnn: "Δακτυλιοειδής έκλειψη Ηλίου – δακτυλιοειδής σε: {r}", partialIn: "Μερική: {r}",
  today: "σήμερα", tomorrow: "αύριο", inDays: "σε {n} ημέρες",
  liveCta: "Δες το τώρα ζωντανά στον ουρανό",
  h2Faq: "Ερωτήσεις & απαντήσεις",
  faq: [
    { q: "Ποιους πλανήτες μπορώ να δω απόψε;", a: "Αλλάζει από εβδομάδα σε εβδομάδα. Αυτή η σελίδα υπολογίζει κάθε ώρα ποιοι πλανήτες βρίσκονται στον βραδινό, νυχτερινό ή πρωινό ουρανό και ποιοι είναι πολύ κοντά στον Ήλιο. Ο Ερμής, η Αφροδίτη, ο Άρης, ο Δίας και ο Κρόνος φαίνονται με γυμνό μάτι." },
    { q: "Πότε είναι η επόμενη πανσέληνος;", a: "Η επόμενη πανσέληνος είναι στις {date}." },
    { q: "Γιατί δεν φαίνονται κάποιοι πλανήτες;", a: "Όταν ένας πλανήτης είναι στον ουρανό πολύ κοντά στον Ήλιο, ανατέλλει και δύει σχεδόν μαζί του και χάνεται στη λάμψη του. Μόνο όταν απομακρυνθεί αρκετά από τον Ήλιο εμφανίζεται ξανά στον βραδινό ή πρωινό ουρανό." },
  ],
  credit: "Θέσεις υπολογισμένες με τους τροχιακούς τύπους του Paul Schlyter (ακρίβεια λίγα πρώτα λεπτά τόξου), όρια αστερισμών της IAU. Εκλείψεις: NASA· βροχές μετεωριτών: IMO.",
  keywords: ["ουρανός απόψε", "ποιοι πλανήτες φαίνονται σήμερα", "φάση σελήνης σήμερα", "επόμενη πανσέληνος", "πανσέληνος οκτώβριος 2026", "διάττοντες 2026", "έκλειψη ηλίου 2027"],
  meteors: { QUA: "Τεταρτημορίδες", LYR: "Λυρίδες", ETA: "Ήτα Υδροχοΐδες", PER: "Περσείδες", ORI: "Ωριωνίδες", LEO: "Λεοντίδες", GEM: "Διδυμίδες" },
  ecl2027aug: ["νότια Ισπανία, Γιβραλτάρ, Μαρόκο, Αλγερία, Τυνησία, Λιβύη, Αίγυπτος, Σαουδική Αραβία, Υεμένη, Σομαλία", "σχεδόν όλη η Ευρώπη, μεγάλο μέρος της Αφρικής, Μέση Ανατολή"],
  ecl2027feb: ["Χιλή, Αργεντινή, Ουρουγουάη, Ακτή Ελεφαντοστού, Γκάνα, Τόγκο, Μπενίν, Νιγηρία", "μεγάλο μέρος της Νότιας Αμερικής και της Δυτικής Αφρικής"],
};

const ar: SkyTodayText = {
  title: "السماء الليلة – ما الكواكب التي تُرى اليوم؟",
  desc: "ما الكواكب المرئية الليلة، وطور القمر اليوم، والبدر القادم، وأحداث السماء القادمة – يُعاد الحساب كل ساعة، مع أوقات الشروق والغروب لموقعك.",
  h1: "السماء الليلة",
  intro: "ما يمكنك رؤيته اليوم في سماء الليل: طور القمر، والكواكب المرئية، وأحداث السماء القادمة – يُعاد حسابها كل ساعة، على الهاتف والكمبيوتر.",
  asOf: "آخر تحديث: {time}",
  moon: "القمر", sun: "الشمس",
  h2Moon: "القمر اليوم", illum: "مضاء بنسبة {pct}٪",
  phases: ["محاق", "هلال متزايد", "تربيع أول", "أحدب متزايد", "بدر", "أحدب متناقص", "تربيع ثانٍ", "هلال متناقص"],
  nextFull: "البدر القادم", nextNew: "المحاق القادم", constLabel: "الكوكبة",
  h2Planets: "ما الكواكب التي تُرى الليلة؟",
  planetsNote: "صالح تقريباً في أي مكان في العالم. أوقات الشروق والغروب الدقيقة لموقعك تجدها في الأسفل.",
  stEveLow: "مساءً بعد غروب الشمس مباشرة، منخفضاً في الغرب", stEve: "في سماء المساء", stAll: "طوال الليل تقريباً", stMorn: "في سماء الصباح", stMornLow: "صباحاً قبيل شروق الشمس، منخفضاً في الشرق", stNone: "غير مرئي – قريب جداً من الشمس",
  eyeNaked: "بالعين المجردة", eyeAid: "بالمنظار أو التلسكوب فقط", brightness: "القدر {m}", showSky: "أرني في السماء",
  h2Local: "الأوقات لموقعك", localBtn: "استخدم موقعي", localHint: "تُحسب الأوقات في متصفحك فقط – لا يُحفظ موقعك ولا يُرسل.", localDenied: "الموقع غير متاح. يرجى السماح بالوصول إلى الموقع.",
  rise: "الشروق", set: "الغروب", none: "—", upAllDay: "لا يغرب",
  h2Events: "أحداث السماء القادمة",
  evFull: "بدر", evNew: "محاق",
  evOpp: "{p} في التقابل – في أشد لمعانه ومرئي طوال الليل",
  evElE: "{p} في أقصى استطالة ({d}°) – أفضل رؤية في سماء المساء",
  evElW: "{p} في أقصى استطالة ({d}°) – أفضل رؤية في سماء الصباح",
  evPair: "{a} و{b} متقاربان جداً ({d}°)",
  evMeteor: "{n}: ذروة زخة الشهب – حتى {z} شهاباً في الساعة في سماء مظلمة",
  meteorMoon: "ضوء القمر: {pct}٪",
  evSolarTotal: "كسوف كلي للشمس – كلي في: {r}", evSolarAnn: "كسوف حلقي للشمس – حلقي في: {r}", partialIn: "جزئي: {r}",
  today: "اليوم", tomorrow: "غداً", inDays: "بعد {n} يوماً",
  liveCta: "شاهده الآن مباشرة في السماء",
  h2Faq: "أسئلة وأجوبة",
  faq: [
    { q: "ما الكواكب التي يمكن رؤيتها الليلة؟", a: "يتغير ذلك من أسبوع لآخر. تحسب هذه الصفحة كل ساعة أي الكواكب في سماء المساء أو الليل أو الصباح وأيها قريب جداً من الشمس. عطارد والزهرة والمريخ والمشتري وزحل تُرى بالعين المجردة." },
    { q: "متى البدر القادم؟", a: "البدر القادم في {date}." },
    { q: "لماذا لا تُرى بعض الكواكب؟", a: "عندما يكون الكوكب قريباً جداً من الشمس في السماء، يشرق ويغرب معها تقريباً ويضيع في وهجها. ولا يظهر من جديد في سماء المساء أو الصباح إلا بعد أن يبتعد عن الشمس بما يكفي." },
  ],
  credit: "المواقع محسوبة بمعادلات المدارات لبول شلايتر (الدقة بضع دقائق قوسية)، وحدود الكوكبات من الاتحاد الفلكي الدولي. الكسوف والخسوف: ناسا؛ زخات الشهب: IMO.",
  keywords: ["السماء الليلة", "ما الكواكب التي ترى اليوم", "طور القمر اليوم", "البدر القادم", "زخة شهب 2026", "كسوف الشمس 2027"],
  meteors: { QUA: "شهب الربعيات", LYR: "شهب القيثاريات", ETA: "شهب إيتا الدلويات", PER: "شهب البرشاويات", ORI: "شهب الجباريات", LEO: "شهب الأسديات", GEM: "شهب التوأميات" },
  ecl2027aug: ["جنوب إسبانيا، جبل طارق، المغرب، الجزائر، تونس، ليبيا، مصر، السعودية، اليمن، الصومال", "أوروبا كلها تقريباً، معظم أفريقيا، الشرق الأوسط"],
  ecl2027feb: ["تشيلي، الأرجنتين، الأوروغواي، ساحل العاج، غانا، توغو، بنين، نيجيريا", "أجزاء كبيرة من أمريكا الجنوبية وغرب أفريقيا"],
};

const hi: SkyTodayText = {
  title: "आज रात का आसमान – आज कौन-से ग्रह दिखेंगे?",
  desc: "आज रात कौन-से ग्रह दिखेंगे, आज चाँद की कला, अगली पूर्णिमा और आने वाली खगोलीय घटनाएँ – हर घंटे नई गणना, आपकी जगह के लिए उदय और अस्त समय के साथ।",
  h1: "आज रात का आसमान",
  intro: "आज रात के आसमान में आप क्या देख सकते हैं: चाँद की कला, दिखने वाले ग्रह और आने वाली खगोलीय घटनाएँ – हर घंटे नई गणना, फ़ोन और PC दोनों पर।",
  asOf: "अपडेट: {time}",
  moon: "चाँद", sun: "सूर्य",
  h2Moon: "आज का चाँद", illum: "{pct}% प्रकाशित",
  phases: ["अमावस्या", "बढ़ता हँसिया चाँद", "प्रथम चतुर्थांश (आधा चाँद)", "बढ़ता हुआ चाँद", "पूर्णिमा", "घटता हुआ चाँद", "अंतिम चतुर्थांश (आधा चाँद)", "घटता हँसिया चाँद"],
  nextFull: "अगली पूर्णिमा", nextNew: "अगली अमावस्या", constLabel: "तारामंडल",
  h2Planets: "आज रात कौन-से ग्रह दिखेंगे?",
  planetsNote: "यह लगभग पूरी दुनिया में लागू है। आपकी जगह के लिए सटीक उदय और अस्त समय नीचे दिए गए हैं।",
  stEveLow: "शाम को सूर्यास्त के ठीक बाद, पश्चिम में नीचे", stEve: "शाम के आसमान में", stAll: "लगभग पूरी रात", stMorn: "सुबह के आसमान में", stMornLow: "सुबह सूर्योदय से ठीक पहले, पूर्व में नीचे", stNone: "नहीं दिखेगा – सूर्य के बहुत पास",
  eyeNaked: "नंगी आँखों से", eyeAid: "सिर्फ़ दूरबीन या टेलीस्कोप से", brightness: "चमक {m} mag", showSky: "आसमान में दिखाएँ",
  h2Local: "आपकी जगह के लिए समय", localBtn: "मेरी लोकेशन इस्तेमाल करें", localHint: "समय सिर्फ़ आपके ब्राउज़र में गणना होता है – आपकी लोकेशन न सेव होती है, न भेजी जाती है।", localDenied: "लोकेशन उपलब्ध नहीं। कृपया लोकेशन की अनुमति दें।",
  rise: "उदय", set: "अस्त", none: "—", upAllDay: "अस्त नहीं होता",
  h2Events: "आने वाली खगोलीय घटनाएँ",
  evFull: "पूर्णिमा", evNew: "अमावस्या",
  evOpp: "{p} विमुखता (opposition) में – सबसे चमकीला और पूरी रात दिखेगा",
  evElE: "{p} सूर्य से सबसे दूर ({d}°) – शाम के आसमान में सबसे अच्छा दृश्य",
  evElW: "{p} सूर्य से सबसे दूर ({d}°) – सुबह के आसमान में सबसे अच्छा दृश्य",
  evPair: "{a} और {b} बहुत पास-पास ({d}°)",
  evMeteor: "{n}: उल्का वर्षा का चरम – अंधेरे आसमान में प्रति घंटे {z} तक टूटते तारे",
  meteorMoon: "चाँदनी: {pct}%",
  evSolarTotal: "पूर्ण सूर्य ग्रहण – पूर्ण रूप में: {r}", evSolarAnn: "वलयाकार सूर्य ग्रहण – वलयाकार रूप में: {r}", partialIn: "आंशिक: {r}",
  today: "आज", tomorrow: "कल", inDays: "{n} दिन में",
  liveCta: "अभी आसमान में लाइव देखें",
  h2Faq: "सवाल और जवाब",
  faq: [
    { q: "आज रात कौन-से ग्रह दिखेंगे?", a: "यह हर हफ़्ते बदलता है। यह पेज हर घंटे गणना करता है कि कौन-से ग्रह शाम, रात या सुबह के आसमान में हैं और कौन-से सूर्य के बहुत पास हैं। बुध, शुक्र, मंगल, बृहस्पति और शनि नंगी आँखों से दिखते हैं।" },
    { q: "अगली पूर्णिमा कब है?", a: "अगली पूर्णिमा {date} को है।" },
    { q: "कुछ ग्रह क्यों नहीं दिखते?", a: "जब कोई ग्रह आसमान में सूर्य के बहुत पास होता है, तो वह लगभग सूर्य के साथ ही उगता और डूबता है और उसकी रोशनी में खो जाता है। सूर्य से काफ़ी दूर होने पर ही वह फिर से शाम या सुबह के आसमान में दिखता है।" },
  ],
  credit: "स्थितियाँ पॉल श्लाइटर के कक्षीय सूत्रों से गणना की गई हैं (सटीकता कुछ चाप-मिनट), तारामंडल सीमाएँ IAU की। ग्रहण: NASA; उल्का वर्षा: IMO।",
  keywords: ["आज रात का आसमान", "आज कौन से ग्रह दिखेंगे", "आज चाँद की कला", "अगली पूर्णिमा", "उल्का वर्षा 2026", "सूर्य ग्रहण 2027"],
  meteors: { QUA: "क्वाड्रैंटिड्स", LYR: "लिरिड्स", ETA: "ईटा एक्वेरिड्स", PER: "पर्सिड्स", ORI: "ओरायनिड्स", LEO: "लियोनिड्स", GEM: "जेमिनिड्स" },
  ecl2027aug: ["दक्षिणी स्पेन, जिब्राल्टर, मोरक्को, अल्जीरिया, ट्यूनीशिया, लीबिया, मिस्र, सऊदी अरब, यमन, सोमालिया", "लगभग पूरा यूरोप, अफ़्रीका का बड़ा हिस्सा, मध्य पूर्व"],
  ecl2027feb: ["चिली, अर्जेंटीना, उरुग्वे, आइवरी कोस्ट, घाना, टोगो, बेनिन, नाइजीरिया", "दक्षिण अमेरिका और पश्चिम अफ़्रीका का बड़ा हिस्सा"],
};

const zh: SkyTodayText = {
  title: "今晚星空 — 今晚能看到哪些行星？",
  desc: "今晚能看到哪些行星、今天的月相、下一次满月和即将到来的天象——每小时重新计算，并提供你所在位置的升落时间。",
  h1: "今晚星空",
  intro: "今天夜空中能看到什么：月相、可见行星和即将到来的天象——每小时重新计算，手机和电脑都能用。",
  asOf: "更新时间：{time}",
  moon: "月球", sun: "太阳",
  h2Moon: "今天的月亮", illum: "被照亮 {pct}%",
  phases: ["新月", "蛾眉月", "上弦月", "盈凸月", "满月", "亏凸月", "下弦月", "残月"],
  nextFull: "下一次满月", nextNew: "下一次新月", constLabel: "星座",
  h2Planets: "今晚能看到哪些行星？",
  planetsNote: "大致适用于全球各地。你所在位置的准确升落时间见下方。",
  stEveLow: "傍晚日落后不久，西方低空", stEve: "在傍晚的天空", stAll: "几乎整夜可见", stMorn: "在清晨的天空", stMornLow: "清晨日出前不久，东方低空", stNone: "不可见——离太阳太近",
  eyeNaked: "肉眼可见", eyeAid: "需要双筒望远镜或天文望远镜", brightness: "亮度 {m} 等", showSky: "在星空中显示",
  h2Local: "你所在位置的时间", localBtn: "使用我的位置", localHint: "时间只在你的浏览器中计算——你的位置不会被保存或发送。", localDenied: "无法获取位置。请允许位置访问。",
  rise: "升起", set: "落下", none: "—", upAllDay: "不落",
  h2Events: "即将到来的天象",
  evFull: "满月", evNew: "新月",
  evOpp: "{p}冲日——最亮且整夜可见",
  evElE: "{p}东大距（{d}°）——傍晚观看的最佳时机",
  evElW: "{p}西大距（{d}°）——清晨观看的最佳时机",
  evPair: "{a}与{b}非常接近（{d}°）",
  evMeteor: "{n}极大——在黑暗天空下每小时最多约 {z} 颗流星",
  meteorMoon: "月光：{pct}%",
  evSolarTotal: "日全食——全食可见于：{r}", evSolarAnn: "日环食——环食可见于：{r}", partialIn: "偏食：{r}",
  today: "今天", tomorrow: "明天", inDays: "{n} 天后",
  liveCta: "现在就在星空中实时查看",
  h2Faq: "常见问题",
  faq: [
    { q: "今晚能看到哪些行星？", a: "每周都会变化。本页面每小时重新计算哪些行星位于傍晚、夜间或清晨的天空，哪些离太阳太近。水星、金星、火星、木星和土星肉眼可见。" },
    { q: "下一次满月是什么时候？", a: "下一次满月在 {date}。" },
    { q: "为什么有些行星看不到？", a: "当行星在天空中离太阳太近时，它几乎与太阳同时升落，被阳光淹没。只有离太阳足够远后，它才会重新出现在傍晚或清晨的天空中。" },
  ],
  credit: "位置根据 Paul Schlyter 的轨道公式计算（精度为几角分），星座边界采用国际天文学联合会标准。日月食：NASA；流星雨：IMO。",
  keywords: ["今晚星空", "今晚能看到哪些行星", "今天月相", "下一次满月", "流星雨 2026", "日全食 2027"],
  meteors: { QUA: "象限仪座流星雨", LYR: "天琴座流星雨", ETA: "宝瓶座η流星雨", PER: "英仙座流星雨", ORI: "猎户座流星雨", LEO: "狮子座流星雨", GEM: "双子座流星雨" },
  ecl2027aug: ["西班牙南部、直布罗陀、摩洛哥、阿尔及利亚、突尼斯、利比亚、埃及、沙特阿拉伯、也门、索马里", "几乎整个欧洲、非洲大部分地区、中东"],
  ecl2027feb: ["智利、阿根廷、乌拉圭、科特迪瓦、加纳、多哥、贝宁、尼日利亚", "南美洲和西非的大部分地区"],
};

const ja: SkyTodayText = {
  title: "今夜の空 — 今夜見える惑星は？",
  desc: "今夜見える惑星、今日の月の満ち欠け、次の満月、これからの天文現象を毎時計算。あなたの場所の出・入りの時刻も表示します。",
  h1: "今夜の空",
  intro: "今日の夜空で見えるもの：月の満ち欠け、見える惑星、これからの天文現象――毎時計算し直し、スマホでもPCでも使えます。",
  asOf: "更新：{time}",
  moon: "月", sun: "太陽",
  h2Moon: "今日の月", illum: "輝面比 {pct}%",
  phases: ["新月", "細い月（満ちていく）", "上弦の月", "満ちていく月", "満月", "欠けていく月", "下弦の月", "細い月（欠けていく）"],
  nextFull: "次の満月", nextNew: "次の新月", constLabel: "星座",
  h2Planets: "今夜見える惑星は？",
  planetsNote: "世界中ほぼどこでも当てはまります。あなたの場所での正確な出・入りの時刻は下にあります。",
  stEveLow: "夕方、日没直後に西の低い空", stEve: "夕方の空", stAll: "ほぼ一晩中", stMorn: "明け方の空", stMornLow: "明け方、日の出直前に東の低い空", stNone: "見えません――太陽に近すぎます",
  eyeNaked: "肉眼で見える", eyeAid: "双眼鏡か望遠鏡が必要", brightness: "明るさ {m} 等", showSky: "星空で表示",
  h2Local: "あなたの場所の時刻", localBtn: "現在地を使う", localHint: "時刻はブラウザ内だけで計算されます――位置情報は保存も送信もされません。", localDenied: "位置情報を取得できません。位置情報へのアクセスを許可してください。",
  rise: "出", set: "入り", none: "—", upAllDay: "沈まない",
  h2Events: "これからの天文現象",
  evFull: "満月", evNew: "新月",
  evOpp: "{p}が衝――最も明るく一晩中見える",
  evElE: "{p}が東方最大離角（{d}°）――夕方の空で見ごろ",
  evElW: "{p}が西方最大離角（{d}°）――明け方の空で見ごろ",
  evPair: "{a}と{b}が大接近（{d}°）",
  evMeteor: "{n}が極大――暗い空なら1時間に最大約{z}個の流れ星",
  meteorMoon: "月明かり：{pct}%",
  evSolarTotal: "皆既日食――皆既が見える地域：{r}", evSolarAnn: "金環日食――金環が見える地域：{r}", partialIn: "部分日食：{r}",
  today: "今日", tomorrow: "明日", inDays: "{n}日後",
  liveCta: "今すぐ星空でライブで見る",
  h2Faq: "よくある質問",
  faq: [
    { q: "今夜はどの惑星が見えますか？", a: "週ごとに変わります。このページは毎時、どの惑星が夕方・夜・明け方の空にあり、どれが太陽に近すぎるかを計算し直しています。水星、金星、火星、木星、土星は肉眼で見えます。" },
    { q: "次の満月はいつですか？", a: "次の満月は{date}です。" },
    { q: "なぜ見えない惑星があるのですか？", a: "空で太陽に近すぎる惑星は、太陽とほぼ同時に昇り沈みするため、太陽の光に埋もれてしまいます。太陽から十分に離れると、再び夕方か明け方の空に現れます。" },
  ],
  credit: "位置はポール・シュライターの軌道計算式で求めています（精度は数分角）。星座境界はIAUによるもの。日食・月食：NASA、流星群：IMO。",
  keywords: ["今夜の空", "今夜見える惑星", "今日の月", "次の満月", "流星群 2026", "皆既日食 2027"],
  meteors: { QUA: "しぶんぎ座流星群", LYR: "こと座流星群", ETA: "みずがめ座η流星群", PER: "ペルセウス座流星群", ORI: "オリオン座流星群", LEO: "しし座流星群", GEM: "ふたご座流星群" },
  ecl2027aug: ["スペイン南部、ジブラルタル、モロッコ、アルジェリア、チュニジア、リビア、エジプト、サウジアラビア、イエメン、ソマリア", "ヨーロッパのほぼ全域、アフリカの大部分、中東"],
  ecl2027feb: ["チリ、アルゼンチン、ウルグアイ、コートジボワール、ガーナ、トーゴ、ベナン、ナイジェリア", "南米と西アフリカの大部分"],
};

const ko: SkyTodayText = {
  title: "오늘 밤 하늘 — 오늘 밤 보이는 행성은?",
  desc: "오늘 밤 보이는 행성, 오늘의 달 위상, 다음 보름달과 다가오는 천문 현상 — 매시간 새로 계산하며 내 위치의 뜨고 지는 시각도 알려 줍니다.",
  h1: "오늘 밤 하늘",
  intro: "오늘 밤하늘에서 볼 수 있는 것: 달의 위상, 보이는 행성, 다가오는 천문 현상 — 매시간 새로 계산하며 휴대폰과 PC에서 모두 볼 수 있습니다.",
  asOf: "업데이트: {time}",
  moon: "달", sun: "태양",
  h2Moon: "오늘의 달", illum: "{pct}% 밝음",
  phases: ["삭(신월)", "초승달", "상현달", "차가는 달", "보름달", "기우는 달", "하현달", "그믐달"],
  nextFull: "다음 보름달", nextNew: "다음 삭(신월)", constLabel: "별자리",
  h2Planets: "오늘 밤 어떤 행성이 보일까?",
  planetsNote: "세계 어디서나 대체로 맞습니다. 내 위치의 정확한 뜨고 지는 시각은 아래에 있습니다.",
  stEveLow: "저녁 해가 진 직후, 서쪽 낮은 하늘", stEve: "저녁 하늘", stAll: "거의 밤새", stMorn: "새벽 하늘", stMornLow: "새벽 해 뜨기 직전, 동쪽 낮은 하늘", stNone: "보이지 않음 — 태양과 너무 가까움",
  eyeNaked: "맨눈으로 보임", eyeAid: "쌍안경이나 망원경 필요", brightness: "밝기 {m}등급", showSky: "하늘에서 보기",
  h2Local: "내 위치의 시각", localBtn: "내 위치 사용", localHint: "시각은 내 브라우저에서만 계산됩니다 — 위치는 저장되거나 전송되지 않습니다.", localDenied: "위치를 가져올 수 없습니다. 위치 접근을 허용해 주세요.",
  rise: "뜨는 시각", set: "지는 시각", none: "—", upAllDay: "지지 않음",
  h2Events: "다가오는 천문 현상",
  evFull: "보름달", evNew: "삭(신월)",
  evOpp: "{p} 충 — 가장 밝고 밤새 보임",
  evElE: "{p} 동방최대이각 ({d}°) — 저녁 하늘에서 가장 잘 보임",
  evElW: "{p} 서방최대이각 ({d}°) — 새벽 하늘에서 가장 잘 보임",
  evPair: "{a}과(와) {b}이(가) 아주 가까이 ({d}°)",
  evMeteor: "{n} 극대 — 어두운 하늘에서 시간당 최대 {z}개의 별똥별",
  meteorMoon: "달빛: {pct}%",
  evSolarTotal: "개기일식 — 개기일식 지역: {r}", evSolarAnn: "금환일식 — 금환일식 지역: {r}", partialIn: "부분일식: {r}",
  today: "오늘", tomorrow: "내일", inDays: "{n}일 후",
  liveCta: "지금 하늘에서 실시간으로 보기",
  h2Faq: "자주 묻는 질문",
  faq: [
    { q: "오늘 밤 어떤 행성을 볼 수 있나요?", a: "주마다 달라집니다. 이 페이지는 매시간 어떤 행성이 저녁·밤·새벽 하늘에 있고 어떤 행성이 태양과 너무 가까운지 새로 계산합니다. 수성, 금성, 화성, 목성, 토성은 맨눈으로 볼 수 있습니다." },
    { q: "다음 보름달은 언제인가요?", a: "다음 보름달은 {date}입니다." },
    { q: "왜 어떤 행성은 안 보이나요?", a: "행성이 하늘에서 태양과 너무 가까우면 태양과 거의 같이 뜨고 지기 때문에 햇빛에 묻혀 보이지 않습니다. 태양에서 충분히 멀어져야 다시 저녁이나 새벽 하늘에 나타납니다." },
  ],
  credit: "위치는 폴 슐라이터의 궤도 공식으로 계산했습니다(정확도 몇 각분). 별자리 경계는 IAU 기준. 일식·월식: NASA, 유성우: IMO.",
  keywords: ["오늘 밤 하늘", "오늘 밤 보이는 행성", "오늘 달 위상", "다음 보름달", "유성우 2026", "개기일식 2027"],
  meteors: { QUA: "사분의자리 유성우", LYR: "거문고자리 유성우", ETA: "물병자리 에타 유성우", PER: "페르세우스자리 유성우", ORI: "오리온자리 유성우", LEO: "사자자리 유성우", GEM: "쌍둥이자리 유성우" },
  ecl2027aug: ["스페인 남부, 지브롤터, 모로코, 알제리, 튀니지, 리비아, 이집트, 사우디아라비아, 예멘, 소말리아", "유럽 거의 전역, 아프리카 대부분, 중동"],
  ecl2027feb: ["칠레, 아르헨티나, 우루과이, 코트디부아르, 가나, 토고, 베냉, 나이지리아", "남아메리카와 서아프리카의 대부분"],
};

const ALL: Record<Lang, SkyTodayText> = { de, en, es, fr, pt, tr, ru, el, ar, hi, zh, ja, ko };

export function skyTodayTexts(lang: Lang): SkyTodayText {
  return ALL[lang] ?? en;
}

export const fill = (s: string, v: Record<string, string | number>) =>
  s.replace(/\{(\w+)\}/g, (_, k) => (k in v ? String(v[k]) : `{${k}}`));
